#!/usr/bin/env python3
from signal import signal, SIGPIPE, SIG_DFL
from sys import argv
from bp.data import data
from bp.map import map_open
from bp.init import init


signal(SIGPIPE, SIG_DFL)

if 'report' == argv[1]:
    for stop in data():
        print(
            ('"' + stop['name'] + '"').ljust(60)
            + '% 10.2fm' % stop['distance'][0]
        )

if 'data' == argv[1]:
    for stop in data():
        print('\t'.join([
            stop['name'],
            '% .2f' % stop['distance'][0],
            '% .7f' % stop['distance'][1][0][0],
            '% .7f' % stop['distance'][1][0][1],
            '% .7f' % stop['distance'][1][1][0],
            '% .7f' % stop['distance'][1][1][1],
        ]))

if 'init' == argv[1]:
    init()

if 'map' == argv[1]:
    map_open(argv[2:])
